#pragma config(Motor,  port3,           mNE,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mSE,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           mSW,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mNW,           tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
*	So how I'm assuming this'll work, we can talk this out:
*
*
*
*/






/*
const float accelWeight = 0.001;

const float jitter = 5;				//PLEASE RENAME THIS, idk what its called

const float wheelDiam = 4;
const float botRadius = 9;

const float motorMultNE = 100;	//Out of 100 (100%), used to adjust for slower motors
const float motorMultNW = 100;	//50% multiplier would be equivalent to 62.5 motor speed
const float motorMultSW = 100;	//when the target speed is 127
const float motorMultSE = 100;

float targetSpeedNE = 0.0;
float targetSpeedSE = 0.0;
float targetSpeedSW = 0.0;
float targetSpeedNW = 0.0;

float smoothSpeedNE = 0.0;
float smoothSpeedSE = 0.0;
float smoothSpeedSW = 0.0;
float smoothSpeedNW = 0.0;
*/
const float s = 1.0 / sqrt(2);
const float wheelDir[2][4]={
	{-s, s},
	{ s, s},
	{-s, s},
	{ s, s}
}; //in the order of: NE, SE, SW, NW

float joyVec[2][2]={
	{0.0, 0.0},
	{0.0, 0.0}
};	//2 Joysticks for 2 vectors. The first (left) provides an xy vector for lateral movement, and the second (right) provides a magnitude on how fast to rotate

float botTargetDir[2]=
	{0.0, 0.0}; 						//(IGNORE)1 vector to determine where the whole bot should move laterally xy, and 1 vectors to determine the direction and speed to

float botInterpDir[2]=
	{0.0, 0.0};							// interpolated verrsion of botTargetDir


float lerp(float a, float b, float weight)
{
	return a * (1 - weight) + b*weight;
}

float length(float x, float y)
{
	//
}

float dot(float ax, float ay, float bx, float by)
{
	//
}

/*
void controllerVector()
{


	botOverallVect[0] = 0;	//Degree
	botOverallVect[1] = 0;	//Magnitude
}
*/

task main()
{
	//get controller joy 1 offset
	joyVec[0][0] = vexRT[Ch4];
	joyVec[1][0] = vexRT[Ch3];

	//set target speed to joy 1 offset
	botTargetVec[0] = joyVec[0][0];
	botTargetVec[1] = joyVec[1][0];

	//set bot vector to interpolated target vector
	botInterpDir = botTargetDir // uh huh uh huh

	//set speed to target speed
	for (int i = 0; i < 4; i++)
	{
		float spd = dot(botTargetVec[0], botTargetVec[1], wheelDir[0][i], wheelDir[1][i]);

		if(i=0)setMotor(3, spd); //speed may need to be multiplied by 128 or somthin
		else if(i=1)setMotor(4, spd);
		else if(i=2)setMotor(5, spd);
		else if(i=3)setMotor(6, spd);
	}



}
