#pragma config(Motor,  port3,           NE,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           SE,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           SW,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           NW,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}
