#pragma config(Sensor, dgtl1,  NEencoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  SEencoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  SWencoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  NWencoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  ESTOPbtn,       sensorTouch)
#pragma config(Sensor, dgtl10, ,               sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, lampENABLE,     sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, lampESTOP,      sensorLEDtoVCC)
#pragma config(Motor,  port3,           NE,            tmotorVex393_MC29, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port4,           SE,            tmotorVex393_MC29, openLoop, encoderPort, dgtl3)
#pragma config(Motor,  port5,           SW,            tmotorVex393_MC29, openLoop, encoderPort, dgtl5)
#pragma config(Motor,  port6,           NW,            tmotorVex393_MC29, openLoop, encoderPort, dgtl7)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



/*----------------*\
|*			SETUP			*|
\*----------------*/

const float tps = 10;
const float tol = 10;
const float motorAngle[4] = {135, -135, -45, 45};

bool eStopState = false;

//Added
float lateralMag[4] = {0.0, 0.0, 0.0, 0.0};

//Speeds
float targetSpeeds[4] ={
	0.0, 0.0, 0.0, 0.0	//Forward
};
float smoothSpeeds[4] ={
	0.0, 0.0, 0.0, 0.0
};



/*----------------*\
|*		FUNCTIONS		*|
\*----------------*/

				void updateMotors()
				{
					motor[NE] = smoothSpeeds[0];
					motor[SE] = smoothSpeeds[1];
					motor[SW] = smoothSpeeds[2];
					motor[NW] = smoothSpeeds[3];
				}
									float cosine(float hyp, float degree)
									{
										float adj = hyp * cos(degree); //Lateral movement speed is the bot's lateralMag times cosine of the lateralDir
										/*if (abs(degree) != degree)
										{
											adj *= -1;	//Flip to negative
										}*/
										if (adj < tol && adj > -tol)
										{
											adj = 0;	//Round to zero
										}
										return adj;
									}//For LeftJoyDir

				void determineLat()
				{
					float latTargetDir = (0);	//Get left joystick direction & magnitude
					float latTargetMag = (70);

					for (int i = 0; i < 4; i++)
					{
						lateralMag[i] = cosine(latTargetMag, motorAngle[i] - latTargetDir) );	//Cosine of magnitude and degree
					}
				}


		void convertAndOutputSmoothSpeed()
		{
			for (int i = 0; i < 4; i++)
			{
				smoothSpeeds[i] = targetSpeeds[i]; //lerp(smoothSpeeds[i], targetSpeeds[i], speedSmoothing);	//Find the speed with acceleration
			}
			updateMotors();
		}

void calculateAll()
{
	determineLat();
	//determineRot();

	//addLatRot();

	//convertForTargetSpeed();

	convertAndOutputSmoothSpeed();
}
void stopAll()
{
	for (int i = 0; i < 4; i++)
	{
		smoothSpeeds[i] = 0; //Stop all motors instantly
	}
	updateMotors();
}


/*----------------*\
|*			Main			*|
\*----------------*/

task main()
{
	while	(true)
	{
		if (vexRT[Btn5U] && vexRT[Btn6U])
		{
			eStopState = false;
			//ledEnable = 3;	//ON
			//ledESTOP = 1;	//Slow Blink
			while (!eStopState)
			{
				if (SensorValue(ESTOPbtn) == 1 || vexRT[Btn5D] == 1 || vexRT[Btn6D] == 1 || vexRT[Btn7D] == 1 || vexRT[Btn8D] == 1)
				{
					eStopState = true;
					//ledESTOP = 3;	//ON
					//ledEnable = 0;	//OFF
				}

				if (!eStopState)
				{
					calculateAll();

					wait1Msec(1000 / tps);	//Msec per tick, inverse of ticks per second
				}
				else
				{
					stopAll();
				}

			}	//While Enable

		}	//Check for Enable

	}	//While Wait For Enable
}	//Task Main
