#pragma config(Sensor, dgtl1,  NEencoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  SEencoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  SWencoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  NWencoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  ESTOPbtn,       sensorTouch)
#pragma config(Sensor, dgtl10, ,               sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, lampENABLE,     sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, lampESTOP,      sensorLEDtoVCC)
#pragma config(Motor,  port3,           NE,            tmotorVex393_MC29, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port4,           SE,            tmotorVex393_MC29, openLoop, encoderPort, dgtl3)
#pragma config(Motor,  port5,           SW,            tmotorVex393_MC29, openLoop, encoderPort, dgtl5)
#pragma config(Motor,  port6,           NW,            tmotorVex393_MC29, openLoop, encoderPort, dgtl7)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*----------------*\
|*			SETUP			*|
\*----------------*/

const float tps = 10;
const float speedSmoothing = 0.25;
const float tol = 10;

bool eStopState = false;

//Added
float rotateMag = 0.0;

//Speeds
float targetSpeeds[4] ={
	0.0, 0.0, 0.0, 0.0
};
float smoothSpeeds[4] ={
	0.0, 0.0, 0.0, 0.0
};



/*----------------*\
|*		FUNCTIONS		*|
\*----------------*/


		float lerp(float a, float b, float weight)	//Acceleration equation
		{
			return a * (1 - weight) + b*weight;
		}
		void updateMotors()
		{
			motor[NE] = smoothSpeeds[0];
			motor[SE] = smoothSpeeds[1];
			motor[SW] = smoothSpeeds[2];
			motor[NW] = smoothSpeeds[3];
		}
		void determineRot()
		{
			if (vexRT[Ch1] <= tol && vexRT[Ch1] >= -tol)
			{
				rotateMag = 0;
			}
			else
			{
				rotateMag = vexRT[Ch1];
			}
		}//For addLatRot


	void convertForTargetSpeed()	//string motorName, float percent, float powerMult, float botMaxSpeed
	{
		determineRot();
		for (int i = 0; i < 4; i++)
		{
			targetSpeeds[i] = rotateMag;	//The target speed is a value between 0 and 1 representing the percent
		}																//times the max speed the bot should ever travel at
	}
	void convertAndOutputSmoothSpeed()
	{
		for (int i = 0; i < 4; i++)
		{
			smoothSpeeds[i] = lerp(smoothSpeeds[i], targetSpeeds[i], speedSmoothing);	//Find the speed with acceleration
		}
		updateMotors();
	}


void calculateAll()
{
	convertForTargetSpeed();

	convertAndOutputSmoothSpeed();
}
void stopAll()
{
	for (int i = 0; i < 4; i++)
	{
		smoothSpeeds[i] = 0; //Stop all motors instantly
	}
	updateMotors();
}


/*----------------*\
|*			Main			*|
\*----------------*/

task main()
{
	while	(true)
	{
		if (vexRT[Btn5U] && vexRT[Btn6U])
		{
			eStopState = false;
			//ledEnable = 3;	//ON
			//ledESTOP = 1;	//Slow Blink
			while (!eStopState)
			{
				if (SensorValue(ESTOPbtn) == 1 || vexRT[Btn5D] == 1 || vexRT[Btn6D] == 1 || vexRT[Btn7D] == 1 || vexRT[Btn8D] == 1)
				{
					eStopState = true;
					//ledESTOP = 3;	//ON
					//ledEnable = 0;	//OFF
				}

				if (!eStopState)
				{
					calculateAll();

					/*if (hybernate)
					{
						wait1Msec(1000 / 2); //2 ticks per second
					}
					else
					{*/
						wait1Msec(1000 / tps);	//Msec per tick, inverse of ticks per second
					//}
				}
				else
				{
					stopAll();
				}

			}	//While Enable

		}	//Check for Enable

	}	//While Wait For Enable
}	//Task Main
